### ISSUE TITLE
AttributeError: 'functools.partial' object has no attribute '__name__'

### ISSUE THREAD

**Issue by papachoco** [NextThought/nti.site#16]
Hi,

When calling the _RunJobInSite.describe_transaction I am getting the error below.

Carlos
```
Traceback (most recent call last):
  File "/home/ntiuser/buildout/sources/nti.metadata/src/nti/metadata/reactor.py", line 76, in process_index_msgs
    result = trx_runner(runner, retries=retries, sleep=sleep)
  File "/home/ntiuser/buildout/eggs/nti.site-1.0.2-py2.7.egg/nti/site/runner.py", line 178, in run_job_in_site
    root_folder_name=root_folder_name)()
  File "/home/ntiuser/buildout/eggs/nti.site-1.0.2-py2.7.egg/nti/site/runner.py", line 128, in __call__
    c.setDebugInfo(self.describe_transaction(*args, **kwargs))
  File "/home/ntiuser/buildout/eggs/nti.site-1.0.2-py2.7.egg/nti/site/runner.py", line 97, in describe_transaction
    name = func.__name__
AttributeError: 'functools.partial' object has no attribute '__name__'
```

**Comment by jamadden** [comment]
Maybe don't pass `functools.partial` objects? The `Transaction.run` method doesn't support them either.

**Comment by papachoco** [comment]
We are passing the partial functions b/c we want to capture the sites before calling the actual function
